name: wf_dev_pr
on:  
  pull_request:
    branches:
      -develop
jobs:
  dev_pr_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Welcom Step
        run: echo "Welcom to the github actions"